# Generated by Django 3.0.8 on 2020-07-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200728_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_item',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('', 'Other')], default='Home', max_length=124),
        ),
    ]
