# Generated by Django 3.0.8 on 2020-07-29 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200729_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_item',
            name='item_creater',
        ),
        migrations.AddField(
            model_name='list_item',
            name='item_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list_item',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Other', 'Other')], default='Home', max_length=124),
        ),
    ]
