# Generated by Django 3.0.8 on 2020-07-31 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200731_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auctions.list_item'),
        ),
    ]
