# Generated by Django 3.0.8 on 2020-07-31 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200731_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_price',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auctions.list_item'),
        ),
    ]
