# Generated by Django 3.0.8 on 2020-08-02 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200731_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_id',
            new_name='bid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
