# Generated by Django 3.0.8 on 2020-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200803_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_item',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
